import Vue from 'vue';
import 'vant/lib/index.css';
import {
    Tabbar,
    TabbarItem,
    NavBar,
    Search,
    Swipe,
    SwipeItem,
    Lazyload,
    Grid,
    GridItem,
    Divider,
    Icon,
    Sticky,
    Toast,
    ImagePreview,
    PullRefresh,
    List,
    GoodsAction,
    GoodsActionIcon,
    GoodsActionButton,
    Sku,
    Card,
    SubmitBar,
    Checkbox,
    CheckboxGroup,
    Stepper,
    SwipeCell,
    Button,
    Form,
    Field,
    Cell,
    CellGroup,
    Image,
    Empty,
    Dialog,
    AddressList,
    AddressEdit,
    Tabs,
    Tab,
    popup,
    Steps,
    Step

} from "vant";


Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(NavBar);
Vue.use(Search);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Lazyload);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Divider);
Vue.use(Icon);
Vue.use(Sticky);
Vue.use(Toast);
Vue.use(ImagePreview);
Vue.use(PullRefresh);
Vue.use(List);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Sku);
Vue.use(Card);
Vue.use(SubmitBar);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Stepper);
Vue.use(SwipeCell);
Vue.use(Button);
Vue.use(Form);
Vue.use(Field);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Image);
Vue.use(Empty);
Vue.use(Dialog);
Vue.use(AddressList);
Vue.use(AddressEdit);
Vue.use(Tabs);
Vue.use(Tab);
Vue.use(popup);
Vue.use(Steps);
Vue.use(Step);